export default [
  {
    "_id": "A101",
    "title": "Propulsion Assignment",
    "course": "RS101",
    "points": 100,
    "startDate": "May 20",
    "startTime": "12:00am",
    "dueDate": "June 10",
    "dueTime": "11:59pm",
    "description": "This assignment will test your understanding of propulsion systems. You will be required to answer a series of questions and submit your answers in a PDF document. The assignment is worth 100 points and is due on June 10th at 11:59pm."
  },
  {
    "_id": "A102",
    "title": "Combustion Analysis",
    "course": "RS101",
    "points": 100,
    "startDate": "May 21",
    "startTime": "12:00am",
    "dueDate": "June 15",
    "dueTime": "11:59pm",
    "description": "Analyze the combustion process in different types of rocket engines. Submit your detailed analysis and findings in a PDF document. This assignment is worth 100 points and is due on June 15th at 11:59pm."
  },
  {
    "_id": "A103",
    "title": "Nozzle Design Project",
    "course": "RS101",
    "points": 150,
    "startDate": "May 25",
    "startTime": "12:00am",
    "dueDate": "June 20",
    "dueTime": "11:59pm",
    "description": "Design a nozzle for a rocket engine and provide detailed specifications and calculations. Include diagrams and a comprehensive report in your submission. This project is worth 150 points and is due on June 20th at 11:59pm."
  },
  {
    "_id": "A201",
    "title": "Aerodynamics Quiz",
    "course": "RS102",
    "points": 50,
    "startDate": "June 1",
    "startTime": "12:00am",
    "dueDate": "June 10",
    "dueTime": "11:59pm",
    "description": "Complete the quiz on fundamental aerodynamic principles. The quiz consists of multiple-choice questions and is worth 50 points. It is due on June 10th at 11:59pm."
  },
  {
    "_id": "A202",
    "title": "Flow Analysis",
    "course": "RS102",
    "points": 100,
    "startDate": "June 5",
    "startTime": "12:00am",
    "dueDate": "June 20",
    "dueTime": "11:59pm",
    "description": "Analyze the airflow over different airfoil designs. Submit a detailed report of your findings, including graphs and charts. This assignment is worth 100 points and is due on June 20th at 11:59pm."
  },
  {
    "_id": "A203",
    "title": "Heating Analysis",
    "course": "RS102",
    "points": 100,
    "startDate": "June 10",
    "startTime": "12:00am",
    "dueDate": "June 25",
    "dueTime": "11:59pm",
    "description": "Analyze the aerodynamic heating effects on various spacecraft surfaces. Provide a detailed report including calculations and mitigation strategies. This assignment is worth 100 points and is due on June 25th at 11:59pm."
  },
  {
    "_id": "A301",
    "title": "Structural Design Task",
    "course": "RS103",
    "points": 100,
    "startDate": "July 1",
    "startTime": "12:00am",
    "dueDate": "July 15",
    "dueTime": "11:59pm",
    "description": "Complete the structural design task by designing a small spacecraft structure. Provide detailed schematics and stress analysis. This task is worth 100 points and is due on July 15th at 11:59pm."
  },
  {
    "_id": "A302",
    "title": "Orbital Calculations",
    "course": "RS103",
    "points": 100,
    "startDate": "July 5",
    "startTime": "12:00am",
    "dueDate": "July 20",
    "dueTime": "11:59pm",
    "description": "Perform orbital calculations for a satellite mission. Submit your calculations and mission plan in a detailed report. This assignment is worth 100 points and is due on July 20th at 11:59pm."
  },
  {
    "_id": "A303",
    "title": "Systems Engineering Exam",
    "course": "RS103",
    "points": 150,
    "startDate": "July 10",
    "startTime": "12:00am",
    "dueDate": "July 25",
    "dueTime": "11:59pm",
    "description": "Complete the exam on systems engineering principles. The exam includes multiple-choice questions and short answer sections. It is worth 150 points and is due on July 25th at 11:59pm."
  },
  {
    "_id": "A401",
    "title": "Hydrocarbon Structure Analysis",
    "course": "RS104",
    "points": 100,
    "startDate": "August 1",
    "startTime": "12:00am",
    "dueDate": "August 10",
    "dueTime": "11:59pm",
    "description": "Analyze the structure of various hydrocarbons and provide a detailed report. Include diagrams and explanations of structural differences. This assignment is worth 100 points and is due on August 10th at 11:59pm."
  },
  {
    "_id": "A402",
    "title": "Organic Synthesis Project",
    "course": "RS104",
    "points": 150,
    "startDate": "August 5",
    "startTime": "12:00am",
    "dueDate": "August 20",
    "dueTime": "11:59pm",
    "description": "Design and execute an organic synthesis experiment. Document your process, results, and provide a detailed report. This project is worth 150 points and is due on August 20th at 11:59pm."
  },
  {
    "_id": "A403",
    "title": "Functional Group Identification",
    "course": "RS104",
    "points": 100,
    "startDate": "August 10",
    "startTime": "12:00am",
    "dueDate": "August 25",
    "dueTime": "11:59pm",
    "description": "Identify and analyze functional groups in given organic compounds. Submit a detailed report with your findings. This assignment is worth 100 points and is due on August 25th at 11:59pm."
  },
  {
    "_id": "A501",
    "title": "Coordination Compound Study",
    "course": "RS105",
    "points": 100,
    "startDate": "September 1",
    "startTime": "12:00am",
    "dueDate": "September 10",
    "dueTime": "11:59pm",
    "description": "Study and report on the properties of various coordination compounds. Include diagrams and detailed explanations. This assignment is worth 100 points and is due on September 10th at 11:59pm."
  },
  {
    "_id": "A502",
    "title": "Organometallic Reaction Analysis",
    "course": "RS105",
    "points": 150,
    "startDate": "September 5",
    "startTime": "12:00am",
    "dueDate": "September 20",
    "dueTime": "11:59pm",
    "description": "Analyze organometallic reactions and submit a comprehensive report. Include reaction mechanisms and practical applications. This project is worth 150 points and is due on September 20th at 11:59pm."
  },
  {
    "_id": "A503",
    "title": "Bioinorganic Chemistry Report",
    "course": "RS105",
    "points": 100,
    "startDate": "September 10",
    "startTime": "12:00am",
    "dueDate": "September 25",
    "dueTime": "11:59pm",
    "description": "Write a report on the role of inorganic elements in biological systems. Include case studies and recent research findings. This assignment is worth 100 points and is due on September 25th at 11:59pm."
  },
  {
    "_id": "A601",
    "title": "Thermodynamic Cycle Calculation",
    "course": "RS106",
    "points": 100,
    "startDate": "October 1",
    "startTime": "12:00am",
    "dueDate": "October 10",
    "dueTime": "11:59pm",
    "description": "Calculate the efficiency of various thermodynamic cycles. Submit your detailed calculations and analysis in a report. This assignment is worth 100 points and is due on October 10th at 11:59pm."
  },
  {
    "_id": "A602",
    "title": "Reaction Rate Experiment",
    "course": "RS106",
    "points": 150,
    "startDate": "October 5",
    "startTime": "12:00am",
    "dueDate": "October 20",
    "dueTime": "11:59pm",
    "description": "Conduct an experiment to measure reaction rates and submit a detailed report. Include experimental setup, data, and analysis. This project is worth 150 points and is due on October 20th at 11:59pm."
  },
  {
    "_id": "A603",
    "title": "Quantum Chemistry Problem Set",
    "course": "RS106",
    "points": 100,
    "startDate": "October 10",
    "startTime": "12:00am",
    "dueDate": "October 25",
    "dueTime": "11:59pm",
    "description": "Solve a set of problems related to quantum chemistry. Submit your solutions in a PDF document. This assignment is worth 100 points and is due on October 25th at 11:59pm."
  }
]
